"""Application use cases live here."""

from application.use_cases.tickets import (
    AddMessageToTicketUseCase,
    AddTagToTicketUseCase,
    ApplyMacroToTicketUseCase,
    AssignNextQueuedTicketUseCase,
    AssignTicketToOperatorUseCase,
    AutoEscalateTicketBySLAUseCase,
    AutoReassignTicketBySLAUseCase,
    BasicStatsUseCase,
    CloseTicketUseCase,
    CreateTicketFromClientMessageUseCase,
    EscalateTicketUseCase,
    EvaluateTicketSLAStateUseCase,
    GetNextQueuedTicketUseCase,
    GetTicketDetailsUseCase,
    ListAvailableTagsUseCase,
    ListMacrosUseCase,
    ListQueuedTicketsUseCase,
    ListTicketTagsUseCase,
    RemoveTagFromTicketUseCase,
    ReplyToTicketAsOperatorUseCase,
    RunTicketSLAChecksUseCase,
)

__all__ = [
    "AddMessageToTicketUseCase",
    "AddTagToTicketUseCase",
    "ApplyMacroToTicketUseCase",
    "AssignNextQueuedTicketUseCase",
    "AssignTicketToOperatorUseCase",
    "AutoEscalateTicketBySLAUseCase",
    "AutoReassignTicketBySLAUseCase",
    "BasicStatsUseCase",
    "CloseTicketUseCase",
    "CreateTicketFromClientMessageUseCase",
    "EscalateTicketUseCase",
    "EvaluateTicketSLAStateUseCase",
    "GetNextQueuedTicketUseCase",
    "GetTicketDetailsUseCase",
    "ListAvailableTagsUseCase",
    "ListMacrosUseCase",
    "ListQueuedTicketsUseCase",
    "ListTicketTagsUseCase",
    "ReplyToTicketAsOperatorUseCase",
    "RemoveTagFromTicketUseCase",
    "RunTicketSLAChecksUseCase",
]
